version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/"             # root directory of package.json
    schedule:
      interval: "weekly"       # check once a week
      day: "monday"
      time: "09:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Toronto"